[package]
name = "some_workspace"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "fake_lib.rs"

[dependencies]
memchr = "2.4.1"

[package.metadata.raze]
genmode = "Remote"
workspace_path = "//cargo"
